feat: kbom k8s core-component scan
Signed-off-by: chenk <hen.keinan@gmail.com>

diff --git a/tests/e2e/image-mode/workload/07-assert.yaml b/tests/e2e/image-mode/workload/07-assert.yaml
--- a/tests/e2e/image-mode/workload/07-assert.yaml
+++ b/tests/e2e/image-mode/workload/07-assert.yaml
@@ -2,7 +2,15 @@
 apiVersion: kuttl.dev/v1beta1
 commands:
   - script: >
-      echo "kubectl get clustervulnerabilityreports.aquasecurity.github.io-o wide"
+      cnt="$(kubectl get clustervulnerabilityreports.aquasecurity.github.io clustersbomreport-557764dbc-k8s-cluster \
+        -o=jsonpath='{.report.summary.highCount}')"
+      if [ $cnt -gt 0 ]
 
+      then
+        echo "Pass: ClusterVulnerabilityReport highCount ($cnt) is greater than 0"
+      else
+        echo "Fail: ClusterVulnerabilityReport highCount ($cnt) should be greater than 0"
+        exit 1
+      fi
 kind: TestAssert
 timeout: 30
